# Generated by Django 4.2.7 on 2023-11-04 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 4, 17, 46, 20, 647721, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
