# Generated by Django 4.2.7 on 2023-11-07 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_2',
        ),
        migrations.AddField(
            model_name='room',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_rooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='specialist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_rooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
