# Generated by Django 4.2.7 on 2023-11-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
