# Generated by Django 4.2.7 on 2023-11-09 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_message_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='RoomMessage',
        ),
    ]
