# Generated by Django 4.2.7 on 2023-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пользователь'), (2, 'Эксперт'), (3, 'Психолог')], default=1),
        ),
    ]
